from ..functions.sin_func import sin_diff
from ..functions.cos_func import cos_diff
from ..functions.tan_func import tan_diff
from ..functions.tanh_func import tanh_diff
from ..functions.softmax_func import softmax_diff
from ..functions.sigmoid_func import sigmoid_diff
from ..functions.relu_func import relu_diff
from ..functions.log_func import log_diff
from ..functions.exp_func import exp_diff
