list_twenty_comb = [
    (['10_diamonds', '10_spades', '4_diamonds'], ['6_diamonds', '7_hearts', 'jack_hearts'], ['10_diamonds', '10_spades', '4_diamonds']),
    (['jack_hearts', '3_spades', 'ace_hearts'], ['king_clubs', '8_clubs', 'queen_hearts'], ['jack_hearts', '3_spades', 'ace_hearts']),
    (['7_diamonds', '4_spades', 'jack_clubs'], ['jack_diamonds', 'king_spades', 'king_hearts'], ['jack_diamonds', 'king_spades', 'king_hearts']),
    (['king_diamonds', '8_spades', '10_diamonds'], ['10_clubs', 'queen_spades', '6_hearts'], ['king_diamonds', '8_spades', '10_diamonds']),
    (['9_hearts', '8_spades', '3_hearts'], ['4_diamonds', '8_diamonds', '6_spades'], ['9_hearts', '8_spades', '3_hearts']),
    (['5_hearts', '8_diamonds', '7_spades'], ['2_spades', 'jack_clubs', '4_hearts'], ['2_spades', 'jack_clubs', '4_hearts']),
    (['queen_diamonds', 'ace_spades', '4_clubs'], ['10_clubs', '3_diamonds', '2_clubs'], ['queen_diamonds', 'ace_spades', '4_clubs']),
    (['2_clubs', '2_spades', 'king_clubs', 'ace_diamonds'], ['4_spades', '7_spades', '9_diamonds', 'ace_clubs'], ['2_clubs', '2_spades', 'king_clubs', 'ace_diamonds']),
    (['king_diamonds', 'jack_diamonds', 'king_hearts', 'queen_spades'], ['2_clubs', '10_clubs', '3_spades', '6_hearts'], ['king_diamonds', 'jack_diamonds', 'king_hearts', 'queen_spades']),
    (['ace_spades', '2_hearts', '10_hearts', 'ace_clubs'], ['9_spades', '6_diamonds', '5_clubs', 'jack_spades'], ['ace_spades', '2_hearts', '10_hearts', 'ace_clubs']),
    (['ace_clubs', '8_spades', '7_hearts', 'queen_clubs'], ['queen_hearts', '6_spades', '9_clubs', '7_diamonds'], ['ace_clubs', '8_spades', '7_hearts', 'queen_clubs']),
    (['9_hearts', '9_spades', '7_diamonds', 'ace_spades'], ['king_clubs', '2_hearts', '8_spades', '6_spades'], ['9_hearts', '9_spades', '7_diamonds', 'ace_spades']),
    (['2_diamonds', '8_clubs', '6_spades', '5_diamonds'], ['9_spades', '5_hearts', '2_hearts', 'ace_spades'], ['9_spades', '5_hearts', '2_hearts', 'ace_spades']),
    (['8_hearts', '10_clubs', '5_clubs', '9_spades'], ['6_hearts', '3_hearts', '3_diamonds', '9_clubs'], ['8_hearts', '10_clubs', '5_clubs', '9_spades']),
    (['4_hearts', '7_diamonds', 'queen_diamonds', 'jack_diamonds', '6_spades'], ['6_clubs', '10_diamonds', '2_spades', 'king_spades', 'king_hearts'], ['6_clubs', '10_diamonds', '2_spades', 'king_spades', 'king_hearts']),
    (['2_spades', 'ace_diamonds', '5_diamonds', 'queen_hearts', '2_clubs'], ['king_clubs', 'jack_hearts', '8_diamonds', '7_diamonds', '5_clubs'], ['2_spades', 'ace_diamonds', '5_diamonds', 'queen_hearts', '2_clubs']),
    (['8_hearts', '8_spades', '7_spades', '6_spades', 'ace_hearts'], ['10_diamonds', '9_clubs', '6_diamonds', 'queen_hearts', '4_hearts'], ['8_hearts', '8_spades', '7_spades', '6_spades', 'ace_hearts']),
    (['queen_diamonds', '9_clubs', '7_spades', 'king_hearts', '10_spades'], ['queen_spades', '6_diamonds', '3_clubs', '8_clubs', '7_hearts'], ['queen_diamonds', '9_clubs', '7_spades', 'king_hearts', '10_spades']),
    (['3_spades', '8_hearts', '6_clubs', 'queen_hearts', '8_clubs'], ['king_clubs', '4_hearts', 'queen_clubs', '2_diamonds', '6_spades'], ['3_spades', '8_hearts', '6_clubs', 'queen_hearts', '8_clubs']),
    (['3_hearts', '5_spades', '6_clubs', '8_diamonds', 'jack_clubs'], ['king_diamonds', 'ace_hearts', '4_hearts', '5_hearts', '2_diamonds'], ['king_diamonds', 'ace_hearts', '4_hearts', '5_hearts', '2_diamonds']),
    (['9_hearts', 'jack_clubs', '10_hearts', '3_hearts'], ['4_diamonds', '3_diamonds', '2_diamonds', 'ace_diamonds'], ['4_diamonds', '3_diamonds', '2_diamonds', 'ace_diamonds']),
    (['ace_clubs', '7_clubs', '3_hearts', 'queen_diamonds'], ['king_clubs', '4_spades', 'queen_hearts', '2_hearts'], ['ace_clubs', '7_clubs', '3_hearts', 'queen_diamonds'])
    ]
